# Generated by Django 3.0.5 on 2020-06-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='sname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
